version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always
    environment:
      - OPENROUTER_API_KEY=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

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    restart: always
