version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always
    environment:
      - OPENROUTER_API_KEY=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

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    restart: always
